[theme]
base="light"
primaryColor="#1f77b4"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"


[server]
maxUploadSize = 2
enableCORS = false
headless = true